# Generated by Django 4.2.4 on 2023-08-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='blogpost',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
